feat: 更新

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,9 +34,16 @@ jobs:
       - name: Install COS Command Line Tool
         run: pip install coscmd
 
+      - name: Check Secrets
+        run: |
+          test -n "${{ secrets.COS_SECRET_ID }}" || (echo "Missing COS_SECRET_ID" && exit 1)
+          test -n "${{ secrets.COS_SECRET_KEY }}" || (echo "Missing COS_SECRET_KEY" && exit 1)
+          test -n "${{ secrets.COS_BUCKET_NAME }}" || (echo "Missing COS_BUCKET_NAME" && exit 1)
+          test -n "${{ secrets.COS_BUCKET_REGION }}" || (echo "Missing COS_BUCKET_REGION" && exit 1)
+
       - name: Configure COS
         run: |
-          coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} -s ${{ secrets.TENCENT_SECRET_KEY }} -b ${{ secrets.COS_BUCKET_NAME }} -r ${{ secrets.COS_BUCKET_REGION }}
+          coscmd config -a ${{ secrets.COS_SECRET_ID }} -s ${{ secrets.COS_SECRET_KEY }} -b ${{ secrets.COS_BUCKET_NAME }} -r ${{ secrets.COS_BUCKET_REGION }}
 
       - name: Upload dist To COS
         run: |
